# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='iban',
            field=models.CharField(max_length=35, verbose_name='IBAN'),
        ),
    ]
